/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppToolBack: typeof import('./src/components/PageLayout/AppToolBack.vue')['default']
    AppToolLayout: typeof import('./src/components/PageLayout/AppToolLayout.vue')['default']
    ArtPlayer: typeof import('./src/components/VideoPlayer/ArtPlayer.vue')['default']
    EmptyResult: typeof import('./src/components/Result/EmptyResult.vue')['default']
    HorizontalSplitPanel: typeof import('./src/components/common/HorizontalSplitPanel.vue')['default']
    InfoResult: typeof import('./src/components/Result/InfoResult.vue')['default']
    LoadingResult: typeof import('./src/components/Result/LoadingResult.vue')['default']
    MainLayout: typeof import('./src/components/PageLayout/MainLayout.vue')['default']
    PageLayout: typeof import('./src/components/PageLayout/PageLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubPageLayout: typeof import('./src/components/PageLayout/SubPageLayout.vue')['default']
    SuccessResult: typeof import('./src/components/Result/SuccessResult.vue')['default']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TAvatar: typeof import('tdesign-vue-next')['Avatar']
    TBreadcrumb: typeof import('tdesign-vue-next')['Breadcrumb']
    TBreadcrumbItem: typeof import('tdesign-vue-next')['BreadcrumbItem']
    TButton: typeof import('tdesign-vue-next')['Button']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TDropdownItem: typeof import('tdesign-vue-next')['DropdownItem']
    TDropdownMenu: typeof import('tdesign-vue-next')['DropdownMenu']
    THeader: typeof import('tdesign-vue-next')['Header']
    TInput: typeof import('tdesign-vue-next')['Input']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TSubmenu: typeof import('tdesign-vue-next')['Submenu']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
    VerticalSplitPanel: typeof import('./src/components/common/VerticalSplitPanel.vue')['default']
    XhAvatar: typeof import('./src/components/xiaohei/XhAvatar.vue')['default']
    XhFileSelect: typeof import('./src/components/xiaohei/XhFileSelect.vue')['default']
    XhUploadImage: typeof import('./src/components/xiaohei/XhUploadImage.vue')['default']
  }
}

// For TSX support
declare global {
  const AppToolBack: typeof import('./src/components/PageLayout/AppToolBack.vue')['default']
  const AppToolLayout: typeof import('./src/components/PageLayout/AppToolLayout.vue')['default']
  const ArtPlayer: typeof import('./src/components/VideoPlayer/ArtPlayer.vue')['default']
  const EmptyResult: typeof import('./src/components/Result/EmptyResult.vue')['default']
  const HorizontalSplitPanel: typeof import('./src/components/common/HorizontalSplitPanel.vue')['default']
  const InfoResult: typeof import('./src/components/Result/InfoResult.vue')['default']
  const LoadingResult: typeof import('./src/components/Result/LoadingResult.vue')['default']
  const MainLayout: typeof import('./src/components/PageLayout/MainLayout.vue')['default']
  const PageLayout: typeof import('./src/components/PageLayout/PageLayout.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SubPageLayout: typeof import('./src/components/PageLayout/SubPageLayout.vue')['default']
  const SuccessResult: typeof import('./src/components/Result/SuccessResult.vue')['default']
  const TAside: typeof import('tdesign-vue-next')['Aside']
  const TAvatar: typeof import('tdesign-vue-next')['Avatar']
  const TBreadcrumb: typeof import('tdesign-vue-next')['Breadcrumb']
  const TBreadcrumbItem: typeof import('tdesign-vue-next')['BreadcrumbItem']
  const TButton: typeof import('tdesign-vue-next')['Button']
  const TContent: typeof import('tdesign-vue-next')['Content']
  const TDropdown: typeof import('tdesign-vue-next')['Dropdown']
  const TDropdownItem: typeof import('tdesign-vue-next')['DropdownItem']
  const TDropdownMenu: typeof import('tdesign-vue-next')['DropdownMenu']
  const THeader: typeof import('tdesign-vue-next')['Header']
  const TInput: typeof import('tdesign-vue-next')['Input']
  const TLayout: typeof import('tdesign-vue-next')['Layout']
  const TMenu: typeof import('tdesign-vue-next')['Menu']
  const TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
  const TSubmenu: typeof import('tdesign-vue-next')['Submenu']
  const TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
  const TTabs: typeof import('tdesign-vue-next')['Tabs']
  const VerticalSplitPanel: typeof import('./src/components/common/VerticalSplitPanel.vue')['default']
  const XhAvatar: typeof import('./src/components/xiaohei/XhAvatar.vue')['default']
  const XhFileSelect: typeof import('./src/components/xiaohei/XhFileSelect.vue')['default']
  const XhUploadImage: typeof import('./src/components/xiaohei/XhUploadImage.vue')['default']
}